### ISSUE TITLE
Jenkins can't read log from taskrun, and the build is running all the time

### ISSUE THREAD

**Issue by donhui** [jenkinsci/tekton-client-plugin#179]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.277.3
OS: Linux - 3.10.0-957.21.3.el7.x86_64
---
git-server:1.9
command-launcher:1.2
windows-slaves:1.0
workflow-basic-steps:2.23
pipeline-input-step:2.12
pipeline-model-extensions:1.8.4
apache-httpcomponents-client-4-api:4.5.13-1.0
workflow-cps:2.90
kubernetes-credentials:0.8.0
lockable-resources:2.3
jackson2-api:2.12.3
metrics:4.0.2.6
durable-task:1.35
pipeline-rest-api:2.10
script-security:1.76
configuration-as-code:1.47
popper-api:1.16.1-2
junit:1.49
snakeyaml-api:1.27.0
scm-api:2.6.4
workflow-job:2.40
structs:1.22
matrix-project:1.18
antisamy-markup-formatter:1.1
workflow-scm-step:2.12
icon-shim:1.0.3
jquery-detached:1.2.1
pipeline-stage-tags-metadata:1.8.4
cloudbees-folder:6.15
pipeline-graph-analysis:1.1
jaxb:2.3.0
pipeline-build-step:2.7
plugin-util-api:2.2.0
kubernetes-client-api:4.13.2-1
pipeline-model-api:1.8.4
pipeline-stage-step:2.3
echarts-api:5.1.0-2
handlebars:1.1
credentials:2.3.15
docker-workflow:1.26
trilead-api:1.0.13
bouncycastle-api:2.18
branch-api:2.0.18
jquery3-api:3.6.0-1
matrix-auth:2.6.5
workflow-step-api:2.23
momentjs:1.1
git-client:3.7.1
docker-commons:1.14
ace-editor:1.1
pipeline-model-declarative-agent:1.1.1
workflow-aggregator:2.6
ssh-credentials:1.18.1
workflow-cps-global-lib:2.19
pipeline-stage-view:2.10
git:4.7.1
authentication-tokens:1.4
font-awesome-api:5.15.3-2
kubernetes:1.29.2
workflow-api:2.41
pipeline-milestone-step:1.3.1
pipeline-model-definition:1.8.4
display-url-api:2.3.4
jsch:0.1.55.2
variant:1.4
bootstrap4-api:4.6.0-3
workflow-durable-task-step:2.38
checks-api:1.7.0
workflow-support:3.8
workflow-multibranch:2.20
plain-credentials:1.7
mailer:1.32.1
credentials-binding:1.24
jdk-tool:1.0
tekton-client:1.0.0
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Jenkins was installed by helm, and agents are provided by k8s.
```

### Reproduction steps

job config:
```
<project>
<actions/>
<description/>
<keepDependencies>false</keepDependencies>
<properties/>
<scm class="hudson.scm.NullSCM"/>
<canRoam>true</canRoam>
<disabled>false</disabled>
<blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
<blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
<triggers/>
<concurrentBuild>false</concurrentBuild>
<builders>
<org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw plugin="tekton-client@1.0.0">
<input>apiVersion: tekton.dev/v1beta1 kind: TaskRun metadata: generateName: print-date- spec: taskSpec: description: | A simple task that prints the date. results: - name: current-date-unix-timestamp description: The current date in unix timestamp format - name: current-date-human-readable description: The current date in human readable format steps: - name: print-date-unix-timestamp image: bash:latest script: | #!/usr/bin/env bash date +%s | tee /tekton/results/current-date-unix-timestamp - name: print-date-human-readable image: bash:latest script: | #!/usr/bin/env bash date | tee /tekton/results/current-date-human-readable</input>
<inputType>YAML</inputType>
<namespace>jenkins</namespace>
<clusterName>default</clusterName>
<enableCatalog>false</enableCatalog>
</org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw>
</builders>
<publishers/>
<buildWrappers/>
</project>
```

jenkins log:
```
May 13, 2021 10:41:50 AM INFO hudson.slaves.NodeProvisioner lambda$update$6
default-62k7f provisioning successfully completed. We have now 2 computer(s)
May 13, 2021 10:41:50 AM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Created Pod: kubernetes jenkins/default-62k7f
May 13, 2021 10:41:51 AM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Pod is running: kubernetes jenkins/default-62k7f
May 13, 2021 10:41:53 AM INFO hudson.TcpSlaveAgentListener$ConnectionHandler run
Accepted JNLP4-connect connection #3 from 172.17.0.1/172.17.0.1:31960
May 13, 2021 10:42:05 AM INFO org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw perform
connecting using cluster name default
May 13, 2021 10:42:05 AM INFO org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw runCreate
Got data before enhancement
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: print-date-
spec:
  taskSpec:
    description: |
      A simple task that prints the date.
    results:
      - name: current-date-unix-timestamp
        description: The current date in unix timestamp format
      - name: current-date-human-readable
        description: The current date in human readable format
    steps:
      - name: print-date-unix-timestamp
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          date +%s | tee /tekton/results/current-date-unix-timestamp
      - name: print-date-human-readable
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          date | tee /tekton/results/current-date-human-readable
May 13, 2021 10:42:05 AM INFO org.waveywaves.jenkins.plugins.tekton.client.TektonUtils getKindFromInputStream
Creating from YAML
May 13, 2021 10:42:05 AM INFO org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw runCreate
creating kind taskrun
May 13, 2021 10:42:05 AM INFO org.waveywaves.jenkins.plugins.tekton.client.logwatch.TaskRunLogWatch run
Found 0 pod(s) for taskRun print-date-wkm8n
May 13, 2021 10:42:06 AM INFO org.waveywaves.jenkins.plugins.tekton.client.logwatch.TaskRunLogWatch run
Found 1 pod(s) for taskRun print-date-wkm8n
```

### Results

Expected result:

Jenkins read log from taskrun, and the build is success.

Actual result:

Jenkins can't read log from taskrun, and the build is running all the time.
![image](https://user-images.githubusercontent.com/5702065/118070446-81632b80-b3d8-11eb-85de-1d8f162074a5.png)

build log:
```
Started by user Jenkins Admin
Running as SYSTEM
Agent default-62k7f is provisioned from template default
---
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins/jenkins-jenkins-agent: "true"
    jenkins/label-digest: "3756805d9a07b9b4e6e92045b5d40394dcc52845"
    jenkins/label: "jenkins-jenkins-agent"
  name: "default-62k7f"
spec:
  containers:
  - args:
    - "********"
    - "default-62k7f"
    env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_TUNNEL"
      value: "jenkins-agent.jenkins.svc.cluster.local:50000"
    - name: "JENKINS_AGENT_NAME"
      value: "default-62k7f"
    - name: "JENKINS_NAME"
      value: "default-62k7f"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/home/jenkins"
    - name: "JENKINS_URL"
      value: "http://jenkins.jenkins.svc.cluster.local:8080/"
    image: "jenkins/inbound-agent:4.6-1"
    imagePullPolicy: "IfNotPresent"
    name: "jnlp"
    resources:
      limits:
        memory: "512Mi"
        cpu: "512m"
      requests:
        memory: "512Mi"
        cpu: "512m"
    tty: false
    volumeMounts:
    - mountPath: "/home/jenkins"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins"
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  serviceAccountName: "default"
  volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volume"

Building remotely on default-62k7f (jenkins-jenkins-agent) in workspace /home/jenkins/workspace/test123
```

When I stop the build, build log and jenkins log as follows.

build log:
```
Failed: null
java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Thread.join(Thread.java:1305)
	at java.base/java.lang.Thread.join(Thread.java:1380)
	at org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw.streamTaskRunLogsToConsole(CreateRaw.java:348)
	at org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw.createTaskRun(CreateRaw.java:192)
	at org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw.createWithResourceSpecificClient(CreateRaw.java:164)
	at org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw.runCreate(CreateRaw.java:431)
	at org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw.perform(CreateRaw.java:395)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.Build$BuildExecution.build(Build.java:197)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:513)
	at hudson.model.Run.execute(Run.java:1907)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

[Tekton] Pod jenkins/print-date-wkm8n-pod-hwphh
Build step 'Tekton : Create Resource (Raw)' changed build result to FAILURE
[Tekton] Pod jenkins/print-date-wkm8n-pod-hwphh - Running...
[Tekton] Container jenkins/print-date-wkm8n-pod-hwphh/step-print-date-unix-timestamp
[Tekton] Container jenkins/print-date-wkm8n-pod-hwphh/step-print-date-unix-timestamp - Completed
[Tekton] Container jenkins/print-date-wkm8n-pod-hwphh/step-print-date-human-readable
1620873735
[Tekton] Container jenkins/print-date-wkm8n-pod-hwphh/step-print-date-human-readable - Completed
Thu May 13 02:42:16 UTC 2021
[Tekton] Pod jenkins/print-date-wkm8n-pod-hwphh Status: Succeeded
Finished: FAILURE
REST API
Jenkins 2.277.3
```

jenkins log:
```
May 13, 2021 10:46:38 AM WARNING org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw runCreate
Caught: java.lang.InterruptedException
May 13, 2021 10:46:38 AM INFO org.waveywaves.jenkins.plugins.tekton.client.logwatch.TaskRunLogWatch run
waiting for pod jenkins/print-date-wkm8n-pod-hwphh to start running...
May 13, 2021 10:46:38 AM INFO org.waveywaves.jenkins.plugins.tekton.client.logwatch.TaskRunLogWatch run
waiting for pod: jenkins/print-date-wkm8n-pod-hwphh container: step-print-date-unix-timestamp to start:
May 13, 2021 10:46:38 AM INFO org.waveywaves.jenkins.plugins.tekton.client.logwatch.TaskRunLogWatch lambda$run$1
Found status ContainerStatus(containerID=docker://c02900fdc0ce57e9a3bd20c207aaf9396b281588657c85f1ff99e0901af53d8b, image=bash:latest, imageID=docker-pullable://bash@sha256:7345c7c8e632ed2ed6b81c6e33fb91b56e3985b95d9b94092a82c8220ee8d788, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=step-print-date-unix-timestamp, ready=false, restartCount=0, started=false, state=ContainerState(running=null, terminated=ContainerStateTerminated(containerID=docker://c02900fdc0ce57e9a3bd20c207aaf9396b281588657c85f1ff99e0901af53d8b, exitCode=0, finishedAt=2021-05-13T02:42:15Z, message=[{"key":"current-date-unix-timestamp","value":"1620873735\n","type":"TaskRunResult"},{"key":"StartedAt","value":"2021-05-13T02:42:15.552Z","type":"InternalTektonResult"}], reason=Completed, signal=null, startedAt=2021-05-13T02:42:11Z, additionalProperties={}), waiting=null, additionalProperties={}), additionalProperties={}) for container step-print-date-unix-timestamp
May 13, 2021 10:46:38 AM INFO org.waveywaves.jenkins.plugins.tekton.client.logwatch.TaskRunLogWatch run
waiting for pod: jenkins/print-date-wkm8n-pod-hwphh container: step-print-date-human-readable to start:
May 13, 2021 10:46:38 AM INFO org.waveywaves.jenkins.plugins.tekton.client.logwatch.TaskRunLogWatch lambda$run$1
Found status ContainerStatus(containerID=docker://9ff1a98f063999db9c175761d5e25b98f1cf1f65e59cc45080978d97149f8051, image=bash:latest, imageID=docker-pullable://bash@sha256:7345c7c8e632ed2ed6b81c6e33fb91b56e3985b95d9b94092a82c8220ee8d788, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=step-print-date-human-readable, ready=false, restartCount=0, started=false, state=ContainerState(running=null, terminated=ContainerStateTerminated(containerID=docker://9ff1a98f063999db9c175761d5e25b98f1cf1f65e59cc45080978d97149f8051, exitCode=0, finishedAt=2021-05-13T02:42:16Z, message=[{"key":"current-date-unix-timestamp","value":"1620873735\n","type":"TaskRunResult"},{"key":"current-date-human-readable","value":"Thu May 13 02:42:16 UTC 2021\n","type":"TaskRunResult"},{"key":"StartedAt","value":"2021-05-13T02:42:16.279Z","type":"InternalTektonResult"}], reason=Completed, signal=null, startedAt=2021-05-13T02:42:14Z, additionalProperties={}), waiting=null, additionalProperties={}), additionalProperties={}) for container step-print-date-human-readable
May 13, 2021 10:46:39 AM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Terminating Kubernetes instance for agent default-62k7f
May 13, 2021 10:46:39 AM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave deleteSlavePod
Terminated Kubernetes instance for agent jenkins/default-62k7f
May 13, 2021 10:46:39 AM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Disconnected computer default-62k7f
May 13, 2021 10:46:39 AM INFO jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed
Computer.threadPoolForRemoting [#224] for default-62k7f terminated: java.nio.channels.ClosedChannelException
Jenkins 2.277.3
```
