### ISSUE TITLE
Can't use url format git@git.example.com:username/project.git 

### ISSUE THREAD

**Issue by daixijun** [jenkinsci/tekton-client-plugin#250]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.331
  OS: Linux - 3.10.0-1062.9.1.el7.x86_64
  ---
  ace-editor:1.1
  ansible:1.1
  ansicolor:1.0.1
  antisamy-markup-formatter:2.7
  apache-httpcomponents-client-4-api:4.5.13-1.0
  authentication-tokens:1.4
  authorize-project:1.4.0
  bootstrap4-api:4.6.0-3
  bootstrap5-api:5.1.3-6
  bouncycastle-api:2.25
  branch-api:2.7.0
  build-user-vars-plugin:1.8
  caffeine-api:2.9.2-29.v717aac953ff3
  checks-api:1.7.2
  cloudbees-disk-usage-simple:0.10
  cloudbees-folder:6.714.v79e858ef76a_2
  command-launcher:1.6
  configuration-as-code:1414.v878271fc496f
  credentials:1074.v60e6c29b_b_44b_
  credentials-binding:1.27.1
  dashboard-view:2.19
  dependency-check-jenkins-plugin:5.1.2
  dependency-track:4.1.1
  display-url-api:2.3.5
  docker-commons:1.19
  docker-java-api:3.1.5.2
  docker-plugin:1.2.6
  docker-workflow:1.28
  durable-task:495.v29cd95ec10f2
  echarts-api:5.3.0-2
  embeddable-build-status:2.0.3
  extended-choice-parameter:346.vd87693c5a_86c
  extended-read-permission:3.2
  external-monitor-job:191.v363d0d1efdf8
  favorite:2.4.1
  font-awesome-api:6.0.0-1
  git:4.10.3
  git-client:3.11.0
  git-parameter:0.9.15
  git-server:1.10
  github-api:1.301-378.v9807bd746da5
  gitlab-oauth:1.13
  gitlab-plugin:1.5.28
  google-oauth-plugin:1.0.6
  handlebars:3.0.8
  handy-uri-templates-2-api:2.1.8-1.0
  htmlpublisher:1.29
  http_request:1.14
  hudson-wsclean-plugin:1.0.8
  image-tag-parameter:1.10
  jackson2-api:2.13.2-260.v43d711474c77
  javadoc:217.v905b_86277a_2a_
  javax-activation-api:1.2.0-2
  javax-mail-api:1.6.2-5
  jdk-tool:1.5
  jenkins-design-language:1.25.3
  jersey2-api:2.35-4
  jobConfigHistory:1119.v509e1017356b_
  jquery:1.12.4-1
  jquery-detached:1.2.1
  jquery3-api:3.6.0-2
  jsch:0.1.55.2
  junit:1.56
  kubernetes:3568.vde94f6b_41b_c8
  kubernetes-cli:1.10.3
  kubernetes-client-api:5.12.1-187.v577c3e368fb_6
  kubernetes-credentials:0.9.0
  localization-support:1.1
  localization-zh-cn:1.0.24
  lockable-resources:2.14
  mailer:408.vd726a_1130320
  mapdb-api:1.0.9.0
  matrix-auth:3.1
  matrix-project:758.v7a_ea_491852f3
  maven-plugin:3.18
  metrics:4.1.6.1
  momentjs:1.1.1
  nexus-jenkins-plugin:3.14.401.v1311ea_023ce5
  oauth-credentials:0.5
  okhttp-api:4.9.3-105.vb96869f8ac3a
  pipeline-build-step:2.16
  pipeline-graph-analysis:188.v3a01e7973f2c
  pipeline-input-step:446.vf27b_0b_83500e
  pipeline-milestone-step:100.v60a_03cd446e1
  pipeline-model-api:2.2064.v5eef7d0982b_e
  pipeline-model-definition:2.2064.v5eef7d0982b_e
  pipeline-model-extensions:2.2064.v5eef7d0982b_e
  pipeline-rest-api:2.23
  pipeline-stage-step:291.vf0a8a7aeeb50
  pipeline-stage-tags-metadata:2.2064.v5eef7d0982b_e
  pipeline-stage-view:2.23
  pipeline-utility-steps:2.12.0
  plain-credentials:1.8
  plugin-util-api:2.15.0
  popper-api:1.16.1-2
  popper2-api:2.11.4-1
  prometheus:2.0.11
  pubsub-light:1.16
  resource-disposer:0.17
  role-strategy:3.2.0
  saltstack:3.2.2
  saml:2.296.v0016349946db_
  scm-api:595.vd5a_df5eb_0e39
  script-security:1131.v8b_b_5eda_c328e
  slack:608.v19e3b_44b_b_9ff
  snakeyaml-api:1.29.1
  sonar:2.14
  sse-gateway:1.25
  ssh:2.6.1
  ssh-agent:1.24.1
  ssh-credentials:1.19
  ssh-slaves:1.806.v2253cedd3295
  ssh-steps:2.0.0
  sshd:3.1.0
  structs:308.v852b473a2b8c
  tekton-client:1.0.3
  timestamper:1.17
  token-macro:280.v97a_82642793c
  trilead-api:1.0.13
  variant:1.4
  workflow-aggregator:2.7
  workflow-api:1143.v2d42f1e9dea_5
  workflow-basic-steps:941.vdfe1b_a_132c64
  workflow-cps:2656.vf7a_e7b_75a_457
  workflow-cps-global-lib:564.ve62a_4eb_b_e039
  workflow-durable-task-step:1121.va_65b_d2701486
  workflow-job:1174.vdcb_d054cf74a_
  workflow-multibranch:711.vdfef37cda_816
  workflow-scm-step:2.13
  workflow-step-api:622.vb_8e7c15b_c95a_
  workflow-support:815.vd60466279fc8
  ws-cleanup:0.40
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/3611220/160051509-b31eac6b-39d9-416b-98fe-c52c5e6f233a.png">

### Reproduction steps

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: example-golang-hello-pr-
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-build-bot
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "500Mi"
  pipelineSpec:
    params:
      - description: the unique build number
        name: BUILD_ID
        type: string
      - description: the git sha of the tip of the pull request
        name: PULL_PULL_SHA
        type: string
      - description: git url to clone
        name: REPO_URL
        type: string
    workspaces:
      - name: shared-data
    tasks:
      - name: fetch-repo
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-data
        params:
          - name: url
            value: $(params.REPO_URL)
          - name: revision
            value: $(params.PULL_PULL_SHA)

```

### Expected Results

run pipeline

### Actual Results

[](https://jenkins.verystar.net/job/example-golang-hello-tekton/5/console#)19:20:16  [Pipeline] tektonCreateRaw
19:20:16  Failed: java.net.MalformedURLException: no protocol: git@git.example.com:username/golang-hello.git
19:20:16  java.lang.RuntimeException: java.net.MalformedURLException: no protocol: git@git.example.com:username/golang-hello.git
19:20:16  	at org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw.enhancePipelineRunWithEnvVars(CreateRaw.java:309)
19:20:16  	at org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw.createPipelineRun(CreateRaw.java:249)
19:20:16  	at org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw.createWithResourceSpecificClient(CreateRaw.java:168)
19:20:16  	at org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw.runCreate(CreateRaw.java:429)
19:20:16  	at org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw.perform(CreateRaw.java:393)
19:20:16  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
19:20:16  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
19:20:16  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
19:20:16  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19:20:16  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19:20:16  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
19:20:16  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
19:20:16  	at java.lang.Thread.run(Thread.java:748)
19:20:16  Caused by: java.net.MalformedURLException: no protocol: git@git.verystar.cn:daixijun/golang-hello.git
19:20:16  	at java.net.URL.<init>(URL.java:611)
19:20:16  	at java.net.URL.<init>(URL.java:508)
19:20:16  	at java.net.URL.<init>(URL.java:457)
19:20:16  	at org.waveywaves.jenkins.plugins.tekton.client.build.create.CreateRaw.enhancePipelineRunWithEnvVars(CreateRaw.java:307)
19:20:16  	... 12 more
